#!/bin/bash

./get_deps
echo "Cleaning..."
sleep 2
dotnet clean
echo "Building..."
sleep 2
dotnet build
echo "Publishing..."
sleep 2
dotnet publish -c Release --self-contained -r linux-x64 && cp -r you bin/Debug/net7.0/you
