#!/bin/bash

print green 'Copying..: Newtonsoft.Json.dll'
cp -r -v ../Newtonsoft.Json-13.0.3/bin/Bin/net6.0/Newtonsoft.Json.dll Newtonsoft.Json-13.0.3_net6.0/Newtonsoft.Json.dll

print green 'Copying..: QuickTools.dll'
cp -r -v ../QuickTools/bin/Release/QuickTools.dll QuickTools/QuickTools.dll
